Abc update
vvzunin/CAD_CombinationalCircuits pull request #20
Opened 2024-01-27 11:46 UTC by Fuuulkrum7

Update abc structure

2024-01-27 17:10 UTC, vvzunin requested changes
Вы добавили бинарник в гит: Generator/source/tests/tests

2024-01-27 17:11 UTC, Fuuulkrum7 commented
> Вы добавили бинарник в гит: Generator/source/tests/tests

Наоборот, я его удалил.
Сейчас не стоит эту ветку, наверное, в main, там используется хедер из 20-х плюсов, а их использование как раз завтра хотели обсудить

2024-01-28 19:19 UTC, vvzunin approved these changes, later dismissed

2024-01-29 10:26 UTC, vvzunin approved these changes

2024-01-29 10:27 UTC, merged